### ISSUE TITLE
[Bug]: Investigate and fix "Deploy to Cloudflare workers" job

### ISSUE THREAD

**Issue by AdiRishi** [AdiRishi/turborepo-remote-cache-cloudflare#217]
![Screenshot 2024-01-02 at 2 56 08 pm](https://github.com/AdiRishi/turborepo-remote-cache-cloudflare/assets/8351234/cdbfe52c-ea84-423a-acdf-eee88b22994c)

**Comment by AdiRishi** [comment]
Made an issue + PR in the `wrangler-action` github repo to help debug the problem - https://github.com/cloudflare/wrangler-action/issues/226

**Comment by AdiRishi** [comment]
With `wrangler-action` now updated to show the inner exception, I have a new lead.

```
🔑 Uploading secrets...
  Error: Invalid Version: latest
  ##[debug]TypeError: Invalid Version: latest
  ##[debug]    at new SemVer (file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:3094:13)
  ##[debug]    at compare (file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:3368:32)
  ##[debug]    at gt (file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:3379:29)
  ##[debug]    at semverCompare (file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:28453:24)
  ##[debug]    at uploadSecrets (file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:28653:13)
  ##[debug]    at main (file:///home/runner/work/_actions/cloudflare/wrangler-action/v3/dist/index.mjs:28561:15)
  ::endgroup::
Error: Failed to upload secrets.
Error: 🚨 Action failed
```
